groups:
  - name: paper-trading-safety
    rules:
      # Paper Trading Safety Alerts
      - alert: PaperTradingModeDisabled
        expr: kiro_bot_paper_trading_mode_enabled == 0
        for: 0m
        labels:
          severity: critical
          service: paper-trading
          safety: critical
        annotations:
          summary: "CRITICAL: Paper trading mode is disabled"
          description: "Paper trading mode has been disabled. This may allow real money trading operations. Immediate action required."

      - alert: RealTradingAllowed
        expr: kiro_bot_real_trading_allowed == 1
        for: 0m
        labels:
          severity: critical
          service: paper-trading
          safety: critical
        annotations:
          summary: "CRITICAL: Real trading is allowed"
          description: "Real trading operations are currently allowed. This poses a risk of actual money loss. Immediate action required."

      - alert: UnsafeEnvironmentDetected
        expr: kiro_bot_environment_safety_score < 90
        for: 0m
        labels:
          severity: critical
          service: paper-trading
          safety: critical
        annotations:
          summary: "CRITICAL: Unsafe environment configuration detected"
          description: "Environment safety score is below 90%. Current score: {{ $value }}%. This indicates unsafe configuration that may allow real trading."

      - alert: ProductionAPIKeysDetected
        expr: kiro_bot_production_api_keys_detected == 1
        for: 0m
        labels:
          severity: critical
          service: paper-trading
          safety: critical
        annotations:
          summary: "CRITICAL: Production API keys detected"
          description: "Production API keys have been detected in the system. This may allow real trading operations."

      - alert: RealTradeAttemptBlocked
        expr: rate(kiro_bot_real_trade_attempts_blocked_total[1m]) > 0
        for: 0m
        labels:
          severity: warning
          service: paper-trading
          safety: high
        annotations:
          summary: "Real trade attempt blocked"
          description: "A real trade attempt has been blocked by the paper trading guard. Rate: {{ $value }} attempts per second."

      - alert: PaperTradingGuardFailure
        expr: kiro_bot_paper_trading_guard_active == 0
        for: 0m
        labels:
          severity: critical
          service: paper-trading
          safety: critical
        annotations:
          summary: "CRITICAL: Paper trading guard is not active"
          description: "The paper trading guard middleware is not active. This may allow real trading operations."

      - alert: VirtualBalanceInconsistency
        expr: abs(kiro_bot_virtual_balance_usd - kiro_bot_expected_virtual_balance_usd) > 1000
        for: 5m
        labels:
          severity: warning
          service: paper-trading
          safety: medium
        annotations:
          summary: "Virtual balance inconsistency detected"
          description: "Virtual balance differs from expected balance by more than $1000. Difference: ${{ $value }}"

      - alert: PaperTradingSimulationFailure
        expr: rate(kiro_bot_paper_trading_simulation_errors_total[5m]) > 0.01
        for: 5m
        labels:
          severity: warning
          service: paper-trading
          safety: medium
        annotations:
          summary: "Paper trading simulation errors detected"
          description: "Paper trading simulation error rate is above 0.01 errors per second. Current rate: {{ $value }}"

      - alert: UnauthorizedTradingEndpointAccess
        expr: rate(kiro_bot_unauthorized_trading_access_total[1m]) > 0
        for: 0m
        labels:
          severity: critical
          service: paper-trading
          safety: critical
        annotations:
          summary: "CRITICAL: Unauthorized access to trading endpoints"
          description: "Unauthorized access attempts to trading endpoints detected. Rate: {{ $value }} attempts per second."

      - alert: APIPermissionValidationFailure
        expr: kiro_bot_api_permission_validation_active == 0
        for: 0m
        labels:
          severity: critical
          service: paper-trading
          safety: critical
        annotations:
          summary: "CRITICAL: API permission validation is not active"
          description: "API permission validation system is not active. This may allow unauthorized trading operations."

      - alert: ExcessivePaperTradingVolume
        expr: rate(kiro_bot_paper_trades_total[1h]) > 1000
        for: 10m
        labels:
          severity: warning
          service: paper-trading
          safety: low
        annotations:
          summary: "Excessive paper trading volume"
          description: "Paper trading volume is above 1000 trades per hour for more than 10 minutes. Current rate: {{ $value }} trades/hour"

      - alert: PaperTradingDrawdownHigh
        expr: kiro_bot_paper_trading_drawdown_percent > 50
        for: 5m
        labels:
          severity: warning
          service: paper-trading
          safety: low
        annotations:
          summary: "High paper trading drawdown"
          description: "Paper trading drawdown is above 50% for more than 5 minutes. Current drawdown: {{ $value }}%"

      - alert: VirtualPortfolioValueNegative
        expr: kiro_bot_virtual_balance_usd < 0
        for: 1m
        labels:
          severity: warning
          service: paper-trading
          safety: medium
        annotations:
          summary: "Virtual portfolio value is negative"
          description: "Virtual portfolio value has gone negative. Current value: ${{ $value }}"

      - alert: PaperTradingAuditLogFailure
        expr: rate(kiro_bot_paper_trading_audit_log_errors_total[5m]) > 0
        for: 5m
        labels:
          severity: warning
          service: paper-trading
          safety: medium
        annotations:
          summary: "Paper trading audit log errors"
          description: "Paper trading audit log error rate is above 0 errors per second. Current rate: {{ $value }}"

      - alert: TradingSimulationEngineDown
        expr: kiro_bot_trading_simulation_engine_active == 0
        for: 1m
        labels:
          severity: critical
          service: paper-trading
          safety: critical
        annotations:
          summary: "CRITICAL: Trading simulation engine is down"
          description: "The trading simulation engine is not active. Paper trades cannot be properly simulated."

  - name: paper-trading-business
    rules:
      # Paper Trading Business Logic Alerts
      - alert: LowPaperTradingActivity
        expr: rate(kiro_bot_paper_trades_total[1h]) < 1
        for: 30m
        labels:
          severity: info
          service: paper-trading
          safety: low
        annotations:
          summary: "Low paper trading activity"
          description: "Paper trading activity is below 1 trade per hour for more than 30 minutes. Current rate: {{ $value }} trades/hour"

      - alert: PaperTradingWinRateLow
        expr: kiro_bot_paper_trading_win_rate_percent < 30
        for: 1h
        labels:
          severity: info
          service: paper-trading
          safety: low
        annotations:
          summary: "Low paper trading win rate"
          description: "Paper trading win rate is below 30% for more than 1 hour. Current rate: {{ $value }}%"

      - alert: VirtualBalanceDepletion
        expr: (kiro_bot_virtual_balance_usd / kiro_bot_initial_virtual_balance_usd) * 100 < 20
        for: 5m
        labels:
          severity: warning
          service: paper-trading
          safety: medium
        annotations:
          summary: "Virtual balance severely depleted"
          description: "Virtual balance is below 20% of initial balance. Current percentage: {{ $value }}%"

      - alert: PaperTradingStrategyFailure
        expr: rate(kiro_bot_paper_trading_strategy_errors_total[10m]) > 0.1
        for: 10m
        labels:
          severity: warning
          service: paper-trading
          safety: medium
        annotations:
          summary: "Paper trading strategy errors"
          description: "Paper trading strategy error rate is above 0.1 errors per second. Current rate: {{ $value }}"

      - alert: UnrealisticPaperTradingGains
        expr: (kiro_bot_paper_trading_pnl_usd{period="24h"} / kiro_bot_virtual_balance_usd) * 100 > 100
        for: 5m
        labels:
          severity: warning
          service: paper-trading
          safety: medium
        annotations:
          summary: "Unrealistic paper trading gains detected"
          description: "24-hour paper trading gains exceed 100% of portfolio value. This may indicate simulation errors. Gain percentage: {{ $value }}%"

      - alert: PaperTradingSlippageHigh
        expr: kiro_bot_paper_trading_average_slippage_percent > 5
        for: 10m
        labels:
          severity: warning
          service: paper-trading
          safety: low
        annotations:
          summary: "High paper trading slippage"
          description: "Average paper trading slippage is above 5% for more than 10 minutes. Current slippage: {{ $value }}%"

  - name: paper-trading-monitoring
    rules:
      # Paper Trading Monitoring Health
      - alert: PaperTradingMetricsCollectionFailure
        expr: rate(kiro_bot_paper_trading_metrics_errors_total[5m]) > 0
        for: 5m
        labels:
          severity: warning
          service: monitoring
          safety: medium
        annotations:
          summary: "Paper trading metrics collection errors"
          description: "Paper trading metrics collection error rate is above 0 errors per second. Current rate: {{ $value }}"

      - alert: PaperTradingDashboardDown
        expr: up{job="paper-trading-dashboard"} == 0
        for: 2m
        labels:
          severity: warning
          service: monitoring
          safety: low
        annotations:
          summary: "Paper trading dashboard is down"
          description: "The paper trading monitoring dashboard has been down for more than 2 minutes"

      - alert: PaperTradingAlertingDown
        expr: up{job="paper-trading-alerting"} == 0
        for: 1m
        labels:
          severity: critical
          service: monitoring
          safety: high
        annotations:
          summary: "CRITICAL: Paper trading alerting system is down"
          description: "The paper trading alerting system has been down for more than 1 minute. Safety monitoring is compromised."