groups:
  - name: real-time-data-feeds
    rules:
      # Market Data Feed Alerts
      - alert: BinanceWebSocketDisconnected
        expr: kiro_bot_websocket_connections_active{exchange="binance",status="connected"} == 0
        for: 30s
        labels:
          severity: critical
          service: market-data
          exchange: binance
        annotations:
          summary: "Binance WebSocket connection lost"
          description: "Binance WebSocket connection has been disconnected for more than 30 seconds"

      - alert: KuCoinWebSocketDisconnected
        expr: kiro_bot_websocket_connections_active{exchange="kucoin",status="connected"} == 0
        for: 30s
        labels:
          severity: critical
          service: market-data
          exchange: kucoin
        annotations:
          summary: "KuCoin WebSocket connection lost"
          description: "KuCoin WebSocket connection has been disconnected for more than 30 seconds"

      - alert: MarketDataStale
        expr: time() - kiro_bot_market_data_last_update_timestamp > 60
        for: 1m
        labels:
          severity: warning
          service: market-data
        annotations:
          summary: "Market data is stale"
          description: "No market data updates received for more than 60 seconds. Last update: {{ $value }} seconds ago"

      - alert: MarketDataLatencyExtreme
        expr: histogram_quantile(0.99, rate(kiro_bot_market_data_latency_seconds_bucket[2m])) > 5
        for: 2m
        labels:
          severity: critical
          service: market-data
        annotations:
          summary: "Extreme market data latency"
          description: "99th percentile market data latency is above 5 seconds. Current latency: {{ $value }}s"

      - alert: MarketDataUpdateRateLow
        expr: rate(kiro_bot_market_data_updates_total[5m]) < 0.1
        for: 5m
        labels:
          severity: warning
          service: market-data
        annotations:
          summary: "Low market data update rate"
          description: "Market data update rate is below 0.1 updates per second. Current rate: {{ $value }}"

      - alert: MarketDataUpdateRateHigh
        expr: rate(kiro_bot_market_data_updates_total[1m]) > 1000
        for: 2m
        labels:
          severity: warning
          service: market-data
        annotations:
          summary: "Extremely high market data update rate"
          description: "Market data update rate is above 1000 updates per second. This may indicate data flooding. Current rate: {{ $value }}"

  - name: real-time-data-processing
    rules:
      # Data Processing Alerts
      - alert: MarketDataProcessingBacklog
        expr: kiro_bot_market_data_processing_queue_size > 10000
        for: 2m
        labels:
          severity: warning
          service: data-processing
        annotations:
          summary: "Market data processing backlog"
          description: "Market data processing queue size is above 10,000 items. Current size: {{ $value }}"

      - alert: MarketDataProcessingErrors
        expr: rate(kiro_bot_market_data_processing_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: data-processing
        annotations:
          summary: "Market data processing errors"
          description: "Market data processing error rate is above 0.1 errors per second. Current rate: {{ $value }}"

      - alert: DataNormalizationFailures
        expr: rate(kiro_bot_data_normalization_failures_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          service: data-processing
        annotations:
          summary: "Data normalization failures"
          description: "Data normalization failure rate is above 0.05 failures per second. Current rate: {{ $value }}"

      - alert: PriceDataInconsistency
        expr: kiro_bot_price_data_inconsistency_detected == 1
        for: 1m
        labels:
          severity: warning
          service: data-processing
        annotations:
          summary: "Price data inconsistency detected"
          description: "Inconsistent price data has been detected between exchanges or timeframes"

      - alert: VolumeDataAnomaly
        expr: kiro_bot_volume_data_anomaly_score > 0.9
        for: 2m
        labels:
          severity: warning
          service: data-processing
        annotations:
          summary: "Volume data anomaly detected"
          description: "Volume data anomaly score is above 0.9. Current score: {{ $value }}"

  - name: real-time-data-caching
    rules:
      # Data Caching Alerts
      - alert: MarketDataCacheMissRateHigh
        expr: (rate(kiro_bot_market_data_cache_misses_total[5m]) / rate(kiro_bot_market_data_cache_requests_total[5m])) * 100 > 50
        for: 5m
        labels:
          severity: warning
          service: caching
        annotations:
          summary: "High market data cache miss rate"
          description: "Market data cache miss rate is above 50%. Current rate: {{ $value }}%"

      - alert: MarketDataCacheEvictionRateHigh
        expr: rate(kiro_bot_market_data_cache_evictions_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
          service: caching
        annotations:
          summary: "High market data cache eviction rate"
          description: "Market data cache eviction rate is above 10 evictions per second. Current rate: {{ $value }}"

      - alert: MarketDataCacheMemoryUsageHigh
        expr: kiro_bot_market_data_cache_memory_usage_bytes > 1000000000
        for: 5m
        labels:
          severity: warning
          service: caching
        annotations:
          summary: "High market data cache memory usage"
          description: "Market data cache memory usage is above 1GB. Current usage: {{ $value }} bytes"

      - alert: MarketDataCacheConnectionFailure
        expr: kiro_bot_market_data_cache_connection_active == 0
        for: 1m
        labels:
          severity: critical
          service: caching
        annotations:
          summary: "Market data cache connection failure"
          description: "Connection to market data cache (Redis) has been lost for more than 1 minute"

  - name: real-time-technical-analysis
    rules:
      # Technical Analysis Alerts
      - alert: TechnicalIndicatorCalculationBacklog
        expr: kiro_bot_technical_indicator_calculation_queue_size > 1000
        for: 5m
        labels:
          severity: warning
          service: technical-analysis
        annotations:
          summary: "Technical indicator calculation backlog"
          description: "Technical indicator calculation queue size is above 1000. Current size: {{ $value }}"

      - alert: TechnicalIndicatorCalculationErrors
        expr: rate(kiro_bot_technical_indicator_calculation_errors_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          service: technical-analysis
        annotations:
          summary: "Technical indicator calculation errors"
          description: "Technical indicator calculation error rate is above 0.05 errors per second. Current rate: {{ $value }}"

      - alert: TechnicalIndicatorLatencyHigh
        expr: histogram_quantile(0.95, rate(kiro_bot_technical_indicator_latency_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: technical-analysis
        annotations:
          summary: "High technical indicator calculation latency"
          description: "95th percentile technical indicator calculation latency is above 2 seconds. Current latency: {{ $value }}s"

      - alert: RSICalculationFailure
        expr: rate(kiro_bot_technical_indicator_calculation_errors_total{indicator="rsi"}[5m]) > 0.01
        for: 5m
        labels:
          severity: warning
          service: technical-analysis
          indicator: rsi
        annotations:
          summary: "RSI calculation failures"
          description: "RSI calculation failure rate is above 0.01 failures per second. Current rate: {{ $value }}"

      - alert: MACDCalculationFailure
        expr: rate(kiro_bot_technical_indicator_calculation_errors_total{indicator="macd"}[5m]) > 0.01
        for: 5m
        labels:
          severity: warning
          service: technical-analysis
          indicator: macd
        annotations:
          summary: "MACD calculation failures"
          description: "MACD calculation failure rate is above 0.01 failures per second. Current rate: {{ $value }}"

      - alert: BollingerBandsCalculationFailure
        expr: rate(kiro_bot_technical_indicator_calculation_errors_total{indicator="bollinger_bands"}[5m]) > 0.01
        for: 5m
        labels:
          severity: warning
          service: technical-analysis
          indicator: bollinger_bands
        annotations:
          summary: "Bollinger Bands calculation failures"
          description: "Bollinger Bands calculation failure rate is above 0.01 failures per second. Current rate: {{ $value }}"

  - name: real-time-data-broadcasting
    rules:
      # Data Broadcasting Alerts
      - alert: WebSocketBroadcastLatencyHigh
        expr: histogram_quantile(0.95, rate(kiro_bot_websocket_broadcast_latency_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          service: broadcasting
        annotations:
          summary: "High WebSocket broadcast latency"
          description: "95th percentile WebSocket broadcast latency is above 1 second. Current latency: {{ $value }}s"

      - alert: WebSocketBroadcastErrors
        expr: rate(kiro_bot_websocket_broadcast_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: broadcasting
        annotations:
          summary: "WebSocket broadcast errors"
          description: "WebSocket broadcast error rate is above 0.1 errors per second. Current rate: {{ $value }}"

      - alert: WebSocketClientDisconnectionRateHigh
        expr: rate(kiro_bot_websocket_client_disconnections_total[5m]) > 1
        for: 5m
        labels:
          severity: warning
          service: broadcasting
        annotations:
          summary: "High WebSocket client disconnection rate"
          description: "WebSocket client disconnection rate is above 1 per second. Current rate: {{ $value }}"

      - alert: WebSocketMessageQueueBacklog
        expr: kiro_bot_websocket_message_queue_size > 10000
        for: 2m
        labels:
          severity: warning
          service: broadcasting
        annotations:
          summary: "WebSocket message queue backlog"
          description: "WebSocket message queue size is above 10,000 messages. Current size: {{ $value }}"

      - alert: WebSocketBroadcastRateHigh
        expr: rate(kiro_bot_websocket_messages_total{direction="outbound"}[1m]) > 10000
        for: 2m
        labels:
          severity: warning
          service: broadcasting
        annotations:
          summary: "Extremely high WebSocket broadcast rate"
          description: "WebSocket outbound message rate is above 10,000 messages per second. Current rate: {{ $value }}"

  - name: real-time-data-quality
    rules:
      # Data Quality Alerts
      - alert: MarketDataGapsDetected
        expr: kiro_bot_market_data_gaps_detected_total > 0
        for: 1m
        labels:
          severity: warning
          service: data-quality
        annotations:
          summary: "Market data gaps detected"
          description: "Gaps in market data have been detected. Total gaps: {{ $value }}"

      - alert: DuplicateMarketDataDetected
        expr: rate(kiro_bot_duplicate_market_data_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: data-quality
        annotations:
          summary: "Duplicate market data detected"
          description: "Duplicate market data rate is above 0.1 per second. Current rate: {{ $value }}"

      - alert: MarketDataTimestampDrift
        expr: abs(kiro_bot_market_data_timestamp_drift_seconds) > 5
        for: 2m
        labels:
          severity: warning
          service: data-quality
        annotations:
          summary: "Market data timestamp drift"
          description: "Market data timestamp drift is above 5 seconds. Current drift: {{ $value }}s"

      - alert: MarketDataValidationFailures
        expr: rate(kiro_bot_market_data_validation_failures_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          service: data-quality
        annotations:
          summary: "Market data validation failures"
          description: "Market data validation failure rate is above 0.05 failures per second. Current rate: {{ $value }}"

      - alert: PriceSpikesDetected
        expr: kiro_bot_price_spike_anomalies_detected > 0
        for: 1m
        labels:
          severity: info
          service: data-quality
        annotations:
          summary: "Price spikes detected"
          description: "Unusual price spikes have been detected. Count: {{ $value }}"

  - name: real-time-data-storage
    rules:
      # Data Storage Alerts
      - alert: MarketDataStorageLatencyHigh
        expr: histogram_quantile(0.95, rate(kiro_bot_market_data_storage_latency_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          service: data-storage
        annotations:
          summary: "High market data storage latency"
          description: "95th percentile market data storage latency is above 1 second. Current latency: {{ $value }}s"

      - alert: MarketDataStorageErrors
        expr: rate(kiro_bot_market_data_storage_errors_total[5m]) > 0.01
        for: 5m
        labels:
          severity: warning
          service: data-storage
        annotations:
          summary: "Market data storage errors"
          description: "Market data storage error rate is above 0.01 errors per second. Current rate: {{ $value }}"

      - alert: MarketDataStorageSpaceRunningLow
        expr: kiro_bot_market_data_storage_space_available_bytes < 1000000000
        for: 10m
        labels:
          severity: warning
          service: data-storage
        annotations:
          summary: "Market data storage space running low"
          description: "Available market data storage space is below 1GB. Current available: {{ $value }} bytes"

      - alert: MarketDataRetentionPolicyViolation
        expr: kiro_bot_market_data_retention_policy_violations > 0
        for: 5m
        labels:
          severity: warning
          service: data-storage
        annotations:
          summary: "Market data retention policy violations"
          description: "Market data retention policy violations detected. Count: {{ $value }}"