groups:
  - name: trading-bot-system
    rules:
      # System Health Alerts
      - alert: HighMemoryUsage
        expr: (kiro_bot_memory_usage_bytes{type="system_used"} / kiro_bot_memory_usage_bytes{type="system_total"}) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% for more than 5 minutes. Current usage: {{ $value }}%"

      - alert: CriticalMemoryUsage
        expr: (kiro_bot_memory_usage_bytes{type="system_used"} / kiro_bot_memory_usage_bytes{type="system_total"}) * 100 > 95
        for: 2m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Critical memory usage detected"
          description: "Memory usage is above 95% for more than 2 minutes. Current usage: {{ $value }}%"

      - alert: HighCPUUsage
        expr: kiro_bot_cpu_usage_percent{core="total"} > 80
        for: 10m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 10 minutes. Current usage: {{ $value }}%"

      - alert: HighLoadAverage
        expr: kiro_bot_cpu_usage_percent{core="load_1m"} > 2
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High system load average"
          description: "1-minute load average is above 2.0 for more than 5 minutes. Current load: {{ $value }}"

      - alert: ApplicationDown
        expr: up{job="trading-bot-backend"} == 0
        for: 1m
        labels:
          severity: critical
          service: application
        annotations:
          summary: "Trading bot application is down"
          description: "The trading bot backend application has been down for more than 1 minute"

      - alert: HighErrorRate
        expr: rate(kiro_bot_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: application
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 0.1 errors per second for more than 5 minutes. Current rate: {{ $value }}"

  - name: trading-bot-http
    rules:
      # HTTP Performance Alerts
      - alert: HighHTTPLatency
        expr: histogram_quantile(0.95, rate(kiro_bot_http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: http
        annotations:
          summary: "High HTTP request latency"
          description: "95th percentile HTTP request latency is above 2 seconds for more than 5 minutes. Current latency: {{ $value }}s"

      - alert: HighHTTPErrorRate
        expr: rate(kiro_bot_http_requests_total{status_code=~"5.."}[5m]) / rate(kiro_bot_http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          service: http
        annotations:
          summary: "High HTTP 5xx error rate"
          description: "HTTP 5xx error rate is above 5% for more than 5 minutes. Current rate: {{ $value }}%"

      - alert: CriticalHTTPErrorRate
        expr: rate(kiro_bot_http_requests_total{status_code=~"5.."}[5m]) / rate(kiro_bot_http_requests_total[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
          service: http
        annotations:
          summary: "Critical HTTP 5xx error rate"
          description: "HTTP 5xx error rate is above 10% for more than 2 minutes. Current rate: {{ $value }}%"

      - alert: TooManyHTTPRequests
        expr: rate(kiro_bot_http_requests_total[1m]) > 1000
        for: 5m
        labels:
          severity: warning
          service: http
        annotations:
          summary: "High HTTP request rate"
          description: "HTTP request rate is above 1000 requests per second for more than 5 minutes. Current rate: {{ $value }}"

  - name: trading-bot-database
    rules:
      # Database Alerts
      - alert: DatabaseConnectionsHigh
        expr: kiro_bot_database_connections_active > 80
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "High number of database connections"
          description: "Database connections are above 80 for more than 5 minutes. Current connections: {{ $value }}"

      - alert: SlowDatabaseQueries
        expr: histogram_quantile(0.95, rate(kiro_bot_database_query_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "Slow database queries detected"
          description: "95th percentile database query time is above 1 second for more than 5 minutes. Current time: {{ $value }}s"

      - alert: DatabaseErrors
        expr: rate(kiro_bot_database_errors_total[5m]) > 0.01
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "Database errors detected"
          description: "Database error rate is above 0.01 errors per second for more than 5 minutes. Current rate: {{ $value }}"

  - name: trading-bot-redis
    rules:
      # Redis Alerts
      - alert: RedisConnectionsHigh
        expr: kiro_bot_redis_connections_active > 100
        for: 5m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "High number of Redis connections"
          description: "Redis connections are above 100 for more than 5 minutes. Current connections: {{ $value }}"

      - alert: SlowRedisOperations
        expr: histogram_quantile(0.95, rate(kiro_bot_redis_operation_duration_seconds_bucket[5m])) > 0.1
        for: 5m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Slow Redis operations detected"
          description: "95th percentile Redis operation time is above 0.1 seconds for more than 5 minutes. Current time: {{ $value }}s"

  - name: trading-bot-websocket
    rules:
      # WebSocket Alerts
      - alert: WebSocketConnectionsHigh
        expr: sum(kiro_bot_websocket_connections_active) > 1000
        for: 5m
        labels:
          severity: warning
          service: websocket
        annotations:
          summary: "High number of WebSocket connections"
          description: "Total WebSocket connections are above 1000 for more than 5 minutes. Current connections: {{ $value }}"

      - alert: WebSocketReconnectionsHigh
        expr: rate(kiro_bot_websocket_reconnections_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: websocket
        annotations:
          summary: "High WebSocket reconnection rate"
          description: "WebSocket reconnection rate is above 0.1 per second for more than 5 minutes. Current rate: {{ $value }}"

      - alert: WebSocketErrors
        expr: rate(kiro_bot_websocket_errors_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          service: websocket
        annotations:
          summary: "WebSocket errors detected"
          description: "WebSocket error rate is above 0.05 errors per second for more than 5 minutes. Current rate: {{ $value }}"

  - name: trading-bot-market-data
    rules:
      # Market Data Alerts
      - alert: MarketDataLatencyHigh
        expr: histogram_quantile(0.95, rate(kiro_bot_market_data_latency_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          service: market-data
        annotations:
          summary: "High market data latency"
          description: "95th percentile market data latency is above 1 second for more than 5 minutes. Current latency: {{ $value }}s"

      - alert: MarketDataUpdatesLow
        expr: rate(kiro_bot_market_data_updates_total[5m]) < 1
        for: 10m
        labels:
          severity: warning
          service: market-data
        annotations:
          summary: "Low market data update rate"
          description: "Market data update rate is below 1 per second for more than 10 minutes. Current rate: {{ $value }}"

      - alert: ExchangeConnectionDown
        expr: kiro_bot_websocket_connections_active{status="connected"} == 0
        for: 2m
        labels:
          severity: critical
          service: exchange
        annotations:
          summary: "Exchange connection is down"
          description: "No active exchange connections detected for more than 2 minutes"

  - name: trading-bot-security
    rules:
      # Security Alerts
      - alert: HighSecurityEvents
        expr: rate(kiro_bot_security_events_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "High security event rate"
          description: "Security event rate is above 0.1 events per second for more than 5 minutes. Current rate: {{ $value }}"

      - alert: CriticalSecurityEvents
        expr: rate(kiro_bot_security_events_total{severity="critical"}[1m]) > 0
        for: 0m
        labels:
          severity: critical
          service: security
        annotations:
          summary: "Critical security event detected"
          description: "Critical security events have been detected. Immediate attention required."

      - alert: HighRateLimitHits
        expr: rate(kiro_bot_rate_limit_hits_total[5m]) > 1
        for: 5m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "High rate limit hit rate"
          description: "Rate limit hit rate is above 1 per second for more than 5 minutes. Current rate: {{ $value }}"

      - alert: FailedAuthenticationAttempts
        expr: rate(kiro_bot_authentication_attempts_total{status="failed"}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "High failed authentication rate"
          description: "Failed authentication rate is above 0.1 per second for more than 5 minutes. Current rate: {{ $value }}"

  - name: trading-bot-business
    rules:
      # Business Logic Alerts
      - alert: LowCacheHitRate
        expr: kiro_bot_cache_hit_rate_percent < 70
        for: 10m
        labels:
          severity: warning
          service: cache
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is below 70% for more than 10 minutes. Current rate: {{ $value }}%"

      - alert: HighOrderLatency
        expr: histogram_quantile(0.95, rate(kiro_bot_order_execution_latency_seconds_bucket[5m])) > 5
        for: 5m
        labels:
          severity: warning
          service: trading
        annotations:
          summary: "High order execution latency"
          description: "95th percentile order execution latency is above 5 seconds for more than 5 minutes. Current latency: {{ $value }}s"

      - alert: TechnicalIndicatorLatencyHigh
        expr: histogram_quantile(0.95, rate(kiro_bot_technical_indicator_latency_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          service: technical-analysis
        annotations:
          summary: "High technical indicator calculation latency"
          description: "95th percentile technical indicator calculation latency is above 1 second for more than 5 minutes. Current latency: {{ $value }}s"

      - alert: ExchangeAPIErrors
        expr: rate(kiro_bot_exchange_errors_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          service: exchange
        annotations:
          summary: "High exchange API error rate"
          description: "Exchange API error rate is above 0.05 errors per second for more than 5 minutes. Current rate: {{ $value }}"