apiVersion: 1

contactPoints:
  - orgId: 1
    name: default-receiver
    receivers:
      - uid: default-webhook
        type: webhook
        settings:
          url: http://host.docker.internal:3000/api/monitoring/alerts
          httpMethod: POST
          title: 'Grafana Alert: {{ .GroupLabels.alertname }}'
        disableResolveMessage: false

  - orgId: 1
    name: critical-alerts
    receivers:
      - uid: critical-email
        type: email
        settings:
          addresses: admin@tradingbot.com
          subject: 'CRITICAL ALERT: {{ .GroupLabels.alertname }}'
          message: |
            {{ range .Alerts }}
            **Alert:** {{ .Annotations.summary }}
            **Description:** {{ .Annotations.description }}
            **Severity:** {{ .Labels.severity }}
            **Time:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
            **Labels:** {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
            {{ end }}
        disableResolveMessage: false
      - uid: critical-webhook
        type: webhook
        settings:
          url: http://host.docker.internal:3000/api/monitoring/alerts/critical
          httpMethod: POST
          title: 'CRITICAL: {{ .GroupLabels.alertname }}'
        disableResolveMessage: false
      - uid: critical-slack
        type: slack
        settings:
          url: YOUR_SLACK_WEBHOOK_URL
          channel: '#critical-alerts'
          username: Grafana
          title: 'CRITICAL ALERT'
          text: |
            {{ range .Alerts }}
            :rotating_light: **{{ .Annotations.summary }}**
            {{ .Annotations.description }}
            Severity: {{ .Labels.severity }}
            {{ end }}
        disableResolveMessage: false

  - orgId: 1
    name: trading-team-alerts
    receivers:
      - uid: trading-email
        type: email
        settings:
          addresses: trading-team@tradingbot.com
          subject: 'Trading Alert: {{ .GroupLabels.alertname }}'
          message: |
            Trading system alert requires attention:
            
            {{ range .Alerts }}
            **Alert:** {{ .Annotations.summary }}
            **Description:** {{ .Annotations.description }}
            **Time:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
            {{ end }}
        disableResolveMessage: false
      - uid: trading-webhook
        type: webhook
        settings:
          url: http://host.docker.internal:3000/api/monitoring/alerts/trading
          httpMethod: POST
          title: 'Trading Alert: {{ .GroupLabels.alertname }}'
        disableResolveMessage: false

  - orgId: 1
    name: security-alerts
    receivers:
      - uid: security-email
        type: email
        settings:
          addresses: security@tradingbot.com
          subject: 'SECURITY ALERT: {{ .GroupLabels.alertname }}'
          message: |
            URGENT SECURITY ALERT:
            
            {{ range .Alerts }}
            **Alert:** {{ .Annotations.summary }}
            **Description:** {{ .Annotations.description }}
            **Severity:** {{ .Labels.severity }}
            **Time:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
            
            Immediate investigation required!
            {{ end }}
        disableResolveMessage: false
      - uid: security-webhook
        type: webhook
        settings:
          url: http://host.docker.internal:3000/api/monitoring/alerts/security
          httpMethod: POST
          title: 'SECURITY ALERT: {{ .GroupLabels.alertname }}'
        disableResolveMessage: false

  - orgId: 1
    name: infrastructure-alerts
    receivers:
      - uid: infrastructure-email
        type: email
        settings:
          addresses: infrastructure@tradingbot.com
          subject: 'Infrastructure Alert: {{ .GroupLabels.alertname }}'
          message: |
            Infrastructure issue detected:
            
            {{ range .Alerts }}
            **Alert:** {{ .Annotations.summary }}
            **Description:** {{ .Annotations.description }}
            **Time:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
            {{ end }}
        disableResolveMessage: false

  - orgId: 1
    name: performance-alerts
    receivers:
      - uid: performance-email
        type: email
        settings:
          addresses: performance@tradingbot.com
          subject: 'Performance Alert: {{ .GroupLabels.alertname }}'
          message: |
            Performance issue detected:
            
            {{ range .Alerts }}
            **Alert:** {{ .Annotations.summary }}
            **Description:** {{ .Annotations.description }}
            **Time:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
            {{ end }}
        disableResolveMessage: false

deleteContactPoints: []